language: bash

install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install python3 coreutils
    - pip3 install pyzmq
before_script:
    - git clone https://github.com/bitcoin/bitcoin.git ./bitcoin-core-nightly
    - cd bitcoin-core-nightly
    - export SRCDIR=$(pwd)
    - echo $SRCDIR
    - python3 ../download_latest_nightly.py --bin="${BIN}" --srcdir="${SRCDIR}"
    - export VERSION=$(tail -1 ./version.txt)
    - export BUILDDIR=$(tail -1 ./build_dir.txt)
    - echo $VERSION
    - echo $BUILDDIR
script:
    - ${BUILDDIR}/src/test_bitcoin
    - cd ${SRCDIR}
    - git checkout $VERSION
    - ${SRCDIR}/test/util/bitcoin-util-test.py -v
    - ${SRCDIR}/test/functional/test_runner.py ${TEST_RUNNER_EXTRA}
after_script:
    - cd ${SRCDIR}
    - git log -1
    - cd ${BUILDDIR}
    - $SHASUM ./src/*

jobs:
 include:
 - os: linux
   language: python
   python: '3.8'
   dist: bionic
   arch: amd64
   env: >-
    SHASUM="shasum -a 256"
    TEST_RUNNER_EXTRA="--exclude rpc_bind,feature_config_args"
   install:
    - sudo apt update && sudo apt install flatpak ca-certificates -y
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo --user
    - flatpak install flathub org.bitcoincore.bitcoin-qt -y --user
    - flatpak override org.bitcoincore.bitcoin-qt --filesystem=/tmp/ --user
    - flatpak override org.bitcoincore.bitcoin-qt --filesystem=$PWD --user
   before_script:
    - git clone https://github.com/bitcoin/bitcoin.git ./bitcoin-core-nightly
    - cd bitcoin-core-nightly
    - export SRCDIR=$(pwd)
    - echo $SRCDIR
    - export BUILDDIR="$(pwd)/../flatpak_bin"
    - echo $BUILDDIR
    - export VERSION=$($BUILDDIR/src/bitcoind --version | head -n 1 | sed 's/Bitcoin Core version //g')
    - echo $VERSION
    - python3 ../write_config_ini.py --srcdir="${SRCDIR}" --builddir="${BUILDDIR}"
   script:
    - ${BUILDDIR}/src/test_bitcoin
    - cd ${SRCDIR}
    - git checkout $VERSION
    - ${SRCDIR}/test/functional/test_runner.py ${TEST_RUNNER_EXTRA}
 - os: linux
   language: python
   python: '3.8'
   dist: bionic
   arch: arm64
   env: >-
    SHASUM="shasum -a 256"
    TEST_RUNNER_EXTRA="--exclude rpc_bind,feature_config_args"
   install:
    - sudo apt update && sudo apt install flatpak ca-certificates -y
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo --user
    - flatpak install flathub org.bitcoincore.bitcoin-qt -y --user
    - flatpak override org.bitcoincore.bitcoin-qt --filesystem=/tmp/ --user
    - flatpak override org.bitcoincore.bitcoin-qt --filesystem=$PWD --user
   before_script:
    - git clone https://github.com/bitcoin/bitcoin.git ./bitcoin-core-nightly
    - cd bitcoin-core-nightly
    - export SRCDIR=$(pwd)
    - echo $SRCDIR
    - export BUILDDIR="$(pwd)/../flatpak_bin"
    - echo $BUILDDIR
    - export VERSION=$($BUILDDIR/src/bitcoind --version | head -n 1 | sed 's/Bitcoin Core version //g')
    - echo $VERSION
    - python3 ../write_config_ini.py --srcdir="${SRCDIR}" --builddir="${BUILDDIR}"
   script:
    - ${BUILDDIR}/src/test_bitcoin
    - cd ${SRCDIR}
    - git checkout $VERSION
    - ${SRCDIR}/test/functional/test_runner.py ${TEST_RUNNER_EXTRA}
 - os: linux
   group: edge
   virt: lxd
   language: python
   python: '3.8'
   dist: bionic
   arch: arm64-graviton2
   env: >-
    SHASUM="shasum -a 256"
    TEST_RUNNER_EXTRA="--exclude rpc_bind,feature_config_args"
   install:
    - sudo apt update && sudo apt install flatpak ca-certificates -y
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo --user
    - flatpak install flathub org.bitcoincore.bitcoin-qt -y --user
    - flatpak override org.bitcoincore.bitcoin-qt --filesystem=/tmp/ --user
    - flatpak override org.bitcoincore.bitcoin-qt --filesystem=$PWD --user
   before_script:
    - git clone https://github.com/bitcoin/bitcoin.git ./bitcoin-core-nightly
    - cd bitcoin-core-nightly
    - export SRCDIR=$(pwd)
    - echo $SRCDIR
    - export BUILDDIR="$(pwd)/../flatpak_bin"
    - echo $BUILDDIR
    - export VERSION=$($BUILDDIR/src/bitcoind --version | head -n 1 | sed 's/Bitcoin Core version //g')
    - echo $VERSION
    - python3 ../write_config_ini.py --srcdir="${SRCDIR}" --builddir="${BUILDDIR}"
   script:
    - ${BUILDDIR}/src/test_bitcoin
    - cd ${SRCDIR}
    - git checkout $VERSION
    - ${SRCDIR}/test/functional/test_runner.py ${TEST_RUNNER_EXTRA}
